import Image from "next/image";
import React from "react";
import Image1 from "../../public/images/brands/cameo.png";
import Image9 from "../../public/images/brands/gameshow.png";
import Image3 from "../../public/images/brands/halara.png"; //
import Image16 from "../../public/images/brands/holoash.png"; // 
import Image15 from "../../public/images/brands/infinix.png"; // 
import Image11 from "../../public/images/brands/lifeboard.png"; //
import Image8 from "../../public/images/brands/logitech.png";
import Image17 from "../../public/images/brands/nordvpn.png";
import Image6 from "../../public/images/brands/obs.png"; //
import Image10 from "../../public/images/brands/pretty.png";
import Image5 from "../../public/images/brands/prime.png";
import Image12 from "../../public/images/brands/romwe.png";
import Image4 from "../../public/images/brands/rumble.png"; //
import Image14 from "../../public/images/brands/shein.png"; //
import Image13 from "../../public/images/brands/snapchat.png"; //
import Image18 from "../../public/images/brands/temu.png"; //
import Image7 from "../../public/images/brands/tide.png";
import Image2 from "../../public/images/brands/tiktok.png";
import Image19 from "../../public/images/brands/wondershare.png"; // 
import Image20 from "../../public/images/brands/gfuel.png"; //

const Brands = () => {
  return (
    <>
      <div className="h-[200px] container relative w-full max-w-[1220px] mb-10">
        <div className="brand-wheel overflow-clip scrollbar flex-shrink-0">
          <div className="brand-slide flex-shrink-0 flex flex-row w-max gap-20">
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image1}
              alt="brand"
              width={169}
              height={169}
              objectFit="contain"
            />

            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image2}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image3}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image4}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image5}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image6}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image7}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image8}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image9}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image10}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image11}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image12}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image13}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image14}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image15}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image16}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image17}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image18}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image19}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image20}
              alt="brand"
              width={169}
              height={169}
            />
          </div>
          <div className="brand-slide flex-shrink-0 delay flex pl-20 flex-row w-max gap-20">
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image1}
              alt="brand"
              width={169}
              height={169}
              
            />

            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image2}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image3}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image4}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image5}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image6}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image7}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image8}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image9}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image10}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image11}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image12}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image13}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image14}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image15}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image16}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image17}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image18}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image19}
              alt="brand"
              width={169}
              height={169}
            />
            <Image
              loading="eager"
              quality={100}
              className="logo-div"
              src={Image20}
              alt="brand"
              width={169}
              height={169}
            />
          </div>
        </div>
      </div>
    </>
  );
};

export default Brands;
